#!/bin/bash
# 智能体社区新闻搜集脚本
# 用途：搜集moltbot及类似AI agent社区的新闻动态

set -e

WORKSPACE="/root/.openclaw/workspace"
REPORT_DIR="$WORKSPACE/reports/agent-community-news"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="$REPORT_DIR/news_${TIMESTAMP}.md"

# 创建报告目录
mkdir -p "$REPORT_DIR"

# 记录开始时间
DATE=$(date '+%Y-%m-%d %H:%M:%S')
echo "📰 开始搜集智能体社区新闻..."

# 创建报告头
cat > "$REPORT_FILE" << EOF
# 智能体社区新闻报告

**生成时间:** $DATE
**报告编号:** ${TIMESTAMP}

---

EOF

# 定义要关注的社区
COMMUNITIES=(
    "moltbot"
    "Cloudflare Workers AI"
    "LangChain"
    "AutoGPT"
    "OpenDevin"
    "AutoGen"
    "CrewAI"
    "BabyAGI"
    "OpenAI Agents"
)

# 为每个社区搜集新闻
for community in "${COMMUNITIES[@]}"; do
    echo "🔍 搜集 $community 的新闻..."

    cat >> "$REPORT_FILE" << EOF

## ${community}

EOF

    # 使用openclaw spawn运行子agent来搜集新闻
    # 将结果追加到报告文件
    openclaw agent spawn \
        --task "搜集并总结关于 ${community} 的最新新闻动态（最近1-2个月），包括：
1. 新功能、新玩法或重要更新
2. 新的插件、工具或扩展
3. 广受讨论的issues、话题或争议
4. 社区重要事件或里程碑

要求：
- 使用web_search搜索相关新闻
- 提供简洁的中文总结
- 每个要点用简洁语言描述
- 如果有重要链接，请附上

请直接输出总结内容，不要添加其他问候语。" \
        --label "news-collector-${community}" \
        --cleanup delete > /tmp/news_${community}_${TIMESTAMP}.txt 2>&1 &

    sleep 3  # 避免同时发起太多请求
done

# 等待所有任务完成
echo "⏳ 等待所有搜集任务完成..."
wait

# 收集所有结果
echo "📝 整理搜集结果..."
for community in "${COMMUNITIES[@]}"; do
    echo "📖 添加 ${community} 的内容..."

    # 从临时文件中提取内容
    if [ -f "/tmp/news_${community}_${TIMESTAMP}.txt" ]; then
        # 提取实际的新闻内容（过滤掉工具调用等）
        grep -v "^📦\|^🔧\|^📊\|^⏱️" "/tmp/news_${community}_${TIMESTAMP}.txt" | \
        grep -v "^Tool call:\|^Function call:\|^Response:" | \
        tail -n +5 >> "$REPORT_FILE"
    fi

    echo "" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    # 清理临时文件
    rm -f "/tmp/news_${community}_${TIMESTAMP}.txt"
done

# 添加总结部分
cat >> "$REPORT_FILE" << EOF

## 总结

本报告由 OpenClaw 自动新闻搜集系统生成，涵盖上述智能体社区的最新动态。

**报告数量:** ${#COMMUNITIES[@]} 个社区
**生成方式:** 自动搜集 + AI总结

---

*Generated by OpenClaw Agent News Collector*
EOF

# 复制到最新
cp "$REPORT_FILE" "$REPORT_DIR/latest.md"

# 计算报告大小
REPORT_SIZE=$(du -h "$REPORT_FILE" | cut -f1)

echo ""
echo "✅ 报告生成完成！"
echo "📁 报告位置: $REPORT_FILE"
echo "📄 最新报告: $REPORT_DIR/latest.md"
echo "📊 报告大小: $REPORT_SIZE"
echo ""
echo "📖 查看报告: cat $REPORT_DIR/latest.md"
